name: nf-reclaim

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    - conda-forge::ca-certificates
    - conda-forge::curl
    - conda-forge::jq
    - conda-forge::wget
    - bioconda::diamond
    - pip:
        - "schemist>=0.0.4.post1"
        